name: Deploy to InfinityFree
on:
  push:
    branches:
      - main # אם הענף שלכם בגיט נקרא master, שנו את המילה main ל-master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/   # מעלה את כל הקבצים שלכם ישר לתיקיית השורש בשרת החינמי
